theme: jekyll-theme-leap-day
title: Reading notes
description: Reading notes for 401 Python course in Code Fellows
show_downloads: true
github:
  zip_url: http://example.com/download.zip
  another_url: another value
